# Generated by Django 4.1.3 on 2022-11-23 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product", name="name", field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name="product", name="price", field=models.FloatField(),
        ),
    ]
